name: BdHRDaily
main: eu.bdh.daily.BdHDaily
version: 2.0.0
author: ReLuLu, Clive
api-version: 1.13
description: New version of the daily plugin for the BdHR Server
commands:
  dcheck:
    description: Returns the player to the last triggered checkpoint
    usage: /dcheck
    aliases: